
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExamAndQuiz.Models
{

using System;
    using System.Collections.Generic;
    
public partial class About
{

    public int ID { get; set; }

    public string SehifeBasliq { get; set; }

    public string Haqqimizda { get; set; }

    public string Mobil { get; set; }

    public string WhatsApp { get; set; }

    public string Email { get; set; }

    public string Youtube { get; set; }

    public string Facebook { get; set; }

    public string Unvan { get; set; }

}

}
