
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExamAndQuiz.Models
{

    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Blog
    {

        public int ID { get; set; }

        public string Basliq { get; set; }
        [AllowHtml]
        public string Melumat { get; set; }

        public string FotoURL { get; set; }

        public System.DateTime Tarix { get; set; }

    }

}
