
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExamAndQuiz.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Exam
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Exam()
    {

        this.ExamQuestions = new HashSet<ExamQuestion>();

        this.ExamOptions = new HashSet<ExamOption>();

        this.ExamResults = new HashSet<ExamResult>();

        this.QuestionBanks = new HashSet<QuestionBank>();

        this.PDFFiles = new HashSet<PDFFile>();

        this.StudentActions = new HashSet<StudentAction>();

        this.StudentOptions = new HashSet<StudentOption>();

    }


    public int ID { get; set; }

    public string Ad { get; set; }

    public int SinifID { get; set; }

    public System.DateTime Tarix { get; set; }

    public string Saat { get; set; }

    public int Muddet_deqiqe { get; set; }

    public bool Status { get; set; }

    public bool Giris { get; set; }

    public string FotoURL { get; set; }

    public string PDFFileUrl { get; set; }

    public int TipParametrID { get; set; }

    public int AdminID { get; set; }

    public string Imtahan { get; set; }



    public virtual Admin Admin { get; set; }

    public virtual ExamTypeParameter ExamTypeParameter { get; set; }

    public virtual Grade Grade { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExamOption> ExamOptions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExamResult> ExamResults { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QuestionBank> QuestionBanks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PDFFile> PDFFiles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StudentAction> StudentActions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StudentOption> StudentOptions { get; set; }

}

}
