
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExamAndQuiz.Models
{

    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class ExamRule
    {

        public int ID { get; set; }
        [AllowHtml]
        public string Qayda { get; set; }

        public int Sira { get; set; }

        public bool Cap { get; set; }

        public bool Elan { get; set; }

    }

}
