
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExamAndQuiz.Models
{

    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class ExamQuestion
    {

        public int ID { get; set; }

        public int ImtahanId { get; set; }

        public int FennId { get; set; }

        public int TipId { get; set; }

        public int SualSirasi { get; set; }
        [AllowHtml]

        public string SualMetni { get; set; }
        [AllowHtml]

        public string Cavablar { get; set; }

        public int SualTipi { get; set; }

        public System.DateTime YaranmaTarixi { get; set; }



        public virtual Exam Exam { get; set; }

        public virtual ExamTypeParameter ExamTypeParameter { get; set; }

        public virtual QuestionType QuestionType { get; set; }

        public virtual Subject Subject { get; set; }

    }

}
