
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExamAndQuiz.Models
{

using System;
    using System.Collections.Generic;
    
public partial class StudentOption
{

    public int ID { get; set; }

    public int SagirdID { get; set; }

    public int ImtahanId { get; set; }

    public bool Bitirmek { get; set; }

    public string Cavablar { get; set; }

    public string FennlerUzreNetice { get; set; }

    public Nullable<double> Bal { get; set; }

    public Nullable<System.DateTime> Tarix { get; set; }



    public virtual Exam Exam { get; set; }

    public virtual Student Student { get; set; }

}

}
