
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ExamAndQuiz.Models
{

using System;
    using System.Collections.Generic;
    
public partial class StudentAction
{

    public int ID { get; set; }

    public int StudentID { get; set; }

    public int ImtahanID { get; set; }

    public string GirisKodu { get; set; }

    public Nullable<System.DateTime> Tarix { get; set; }

    public bool Status { get; set; }



    public virtual Exam Exam { get; set; }

    public virtual Student Student { get; set; }

}

}
